language: c
branches:
  only:
    - master
before_install:
  - openssl aes-256-cbc -K $encrypted_521a707df07f_key -iv $encrypted_521a707df07f_iv -in ci.enc -out ci -d
  - wget "https://releases.hashicorp.com/packer/1.1.0/packer_1.1.0_linux_amd64.zip"
  - unzip packer_1.1.0_linux_amd64.zip
  - sudo pip install bumpversion
script:
  - ./packer validate config.json
  - ./packer build config.json
  - git config core.sshCommand "ssh -F ssh_config"
  - bumpversion number
